automation_account_name = "user-offboarding"
runbook_name            = "user-offboarding"
cert_keyvault           = "cftptl-intsvc"
cert_keyvault_rg        = "core-infra-intsvc-rg"
webhook_name            = "webhook"